<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['name' => 'Alaminos', 'country_id' => 175 ],
            ['name' => 'Angeles City', 'country_id' => 175  ],
            ['name' => 'Antipolo', 'country_id' => 175  ],
            ['name' => 'Bacolod', 'country_id' => 175  ],
            ['name' => 'Bacoor', 'country_id' => 175  ],
            ['name' => 'Bago', 'country_id' => 175  ],
            ['name' => 'Baguio', 'country_id' => 175  ],
            ['name' => 'Bais', 'country_id' => 175  ],
            ['name' => 'Balanga', 'country_id' => 175  ],
            ['name' => 'Batac', 'country_id' => 175  ],
            ['name' => 'Batangas City', 'country_id' => 175  ],
            ['name' => 'Bayawan', 'country_id' => 175  ],
            ['name' => 'Baybay', 'country_id' => 175  ],
            ['name' => 'Bayugan', 'country_id' => 175  ],
            ['name' => 'Biñan', 'country_id' => 175  ],
            ['name' => 'Bislig', 'country_id' => 175  ],
            ['name' => 'Bogo', 'country_id' => 175  ],
            ['name' => 'Borongan', 'country_id' => 175  ],
            ['name' => 'Butuan', 'country_id' => 175  ],
            ['name' => 'Cabadbaran', 'country_id' => 175  ],
            ['name' => 'Cabanatuan', 'country_id' => 175  ],
            ['name' => 'Cabuyao', 'country_id' => 175  ],
            ['name' => 'Cadiz', 'country_id' => 175  ],
            ['name' => 'Cagayan de Oro', 'country_id' => 175  ],
            ['name' => 'Calamba', 'country_id' => 175  ],
            ['name' => 'Calapan', 'country_id' => 175  ],
            ['name' => 'Calbayog', 'country_id' => 175  ],
            ['name' => 'Caloocan', 'country_id' => 175  ],
            ['name' => 'Candon', 'country_id' => 175  ],
            ['name' => 'Canlaon', 'country_id' => 175  ],
            ['name' => 'Carcar', 'country_id' => 175  ],
            ['name' => 'Catbalogan', 'country_id' => 175  ],
            ['name' => 'Cauayan', 'country_id' => 175  ],
            ['name' => 'Cavite City', 'country_id' => 175  ],
            ['name' => 'Cebu City', 'country_id' => 175  ],
            ['name' => 'Cotabato City', 'country_id' => 175  ],
            ['name' => 'Dagupan', 'country_id' => 175  ],
            ['name' => 'Danao', 'country_id' => 175  ],
            ['name' => 'Dapitan', 'country_id' => 175  ],
            ['name' => 'Dasmariñas', 'country_id' => 175  ],
            ['name' => 'Davao City', 'country_id' => 175  ],
            ['name' => 'Digos', 'country_id' => 175  ],
            ['name' => 'Dipolog', 'country_id' => 175  ],
            ['name' => 'Dumaguete', 'country_id' => 175  ],
            ['name' => 'El Salvador', 'country_id' => 175  ],
            ['name' => 'Escalante', 'country_id' => 175  ],
            ['name' => 'Gapan', 'country_id' => 175  ],
            ['name' => 'General Santos', 'country_id' => 175  ],
            ['name' => 'General Trias', 'country_id' => 175  ],
            ['name' => 'Gingoog', 'country_id' => 175  ],
            ['name' => 'Guihulngan', 'country_id' => 175  ],
            ['name' => 'Himamaylan', 'country_id' => 175  ],
            ['name' => 'Ilagan', 'country_id' => 175  ],
            ['name' => 'Iligan', 'country_id' => 175  ],
            ['name' => 'Iloilo City', 'country_id' => 175  ],
            ['name' => 'Imus', 'country_id' => 175  ],
            ['name' => 'Iriga', 'country_id' => 175  ],
            ['name' => 'Isabela', 'country_id' => 175  ],
            ['name' => 'Kabankalan', 'country_id' => 175  ],
            ['name' => 'Kidapawan', 'country_id' => 175  ],
            ['name' => 'Koronadal', 'country_id' => 175  ],
            ['name' => 'La Carlota', 'country_id' => 175  ],
            ['name' => 'Lamitan', 'country_id' => 175  ],
            ['name' => 'Laoag', 'country_id' => 175  ],
            ['name' => 'Lapu-Lapu City', 'country_id' => 175  ],
            ['name' => 'Las Piñas', 'country_id' => 175  ],
            ['name' => 'Legazpi', 'country_id' => 175  ],
            ['name' => 'Ligao', 'country_id' => 175  ],
            ['name' => 'Lipa', 'country_id' => 175  ],
            ['name' => 'Lucena', 'country_id' => 175  ],
            ['name' => 'Maasin', 'country_id' => 175  ],
            ['name' => 'Mabalacat', 'country_id' => 175  ],
            ['name' => 'Makati', 'country_id' => 175  ],
            ['name' => 'Malabon', 'country_id' => 175  ],
            ['name' => 'Malaybalay', 'country_id' => 175  ],
            ['name' => 'Malolos', 'country_id' => 175  ],
            ['name' => 'Mandaluyong', 'country_id' => 175  ],
            ['name' => 'Mandaue', 'country_id' => 175  ],
            ['name' => 'Manila', 'country_id' => 175  ],
            ['name' => 'Marawi', 'country_id' => 175  ],
            ['name' => 'Marikina', 'country_id' => 175  ],
            ['name' => 'Masbate City', 'country_id' => 175  ],
            ['name' => 'Mati', 'country_id' => 175  ],
            ['name' => 'Meycauayan', 'country_id' => 175  ],
            ['name' => 'Muñoz', 'country_id' => 175  ],
            ['name' => 'Muntinlupa', 'country_id' => 175  ],
            ['name' => 'Naga', 'country_id' => 175  ],
            ['name' => 'Naga', 'country_id' => 175  ],
            ['name' => 'Navotas', 'country_id' => 175  ],
            ['name' => 'Olongapo', 'country_id' => 175  ],
            ['name' => 'Ormoc', 'country_id' => 175  ],
            ['name' => 'Oroquieta', 'country_id' => 175  ],
            ['name' => 'Ozamiz', 'country_id' => 175  ],
            ['name' => 'Pagadian', 'country_id' => 175  ],
            ['name' => 'Palayan', 'country_id' => 175  ],
            ['name' => 'Panabo', 'country_id' => 175  ],
            ['name' => 'Parañaque', 'country_id' => 175  ],
            ['name' => 'Pasay', 'country_id' => 175  ],
            ['name' => 'Pasig', 'country_id' => 175  ],
            ['name' => 'Passi', 'country_id' => 175  ],
            ['name' => 'Puerto Princesa', 'country_id' => 175  ],
            ['name' => 'Quezon City', 'country_id' => 175  ],
            ['name' => 'Roxas', 'country_id' => 175  ],
            ['name' => 'Sagay', 'country_id' => 175  ],
            ['name' => 'Samal', 'country_id' => 175  ],
            ['name' => 'San Carlos', 'country_id' => 175  ],
            ['name' => 'San Carlos', 'country_id' => 175  ],
            ['name' => 'San Fernando', 'country_id' => 175  ],
            ['name' => 'San Fernando', 'country_id' => 175  ],
            ['name' => 'San Jose', 'country_id' => 175  ],
            ['name' => 'San Jose del Monte', 'country_id' => 175  ],
            ['name' => 'San Juan', 'country_id' => 175  ],
            ['name' => 'San Pablo', 'country_id' => 175  ],
            ['name' => 'San Pedro', 'country_id' => 175  ],
            ['name' => 'Santa Rosa', 'country_id' => 175  ],
            ['name' => 'Santo Tomas', 'country_id' => 175  ],
            ['name' => 'Santiago', 'country_id' => 175  ],
            ['name' => 'Silay', 'country_id' => 175  ],
            ['name' => 'Sipalay', 'country_id' => 175  ],
            ['name' => 'Sorsogon City', 'country_id' => 175  ],
            ['name' => 'Surigao City', 'country_id' => 175  ],
            ['name' => 'Tabaco', 'country_id' => 175  ],
            ['name' => 'Tabuk', 'country_id' => 175  ],
            ['name' => 'Tacloban', 'country_id' => 175  ],
            ['name' => 'Tacurong', 'country_id' => 175  ],
            ['name' => 'Tagaytay', 'country_id' => 175  ],
            ['name' => 'Tagbilaran', 'country_id' => 175  ],
            ['name' => 'Taguig', 'country_id' => 175  ],
            ['name' => 'Tagum', 'country_id' => 175  ],
            ['name' => 'Talisay', 'country_id' => 175  ],
            ['name' => 'Talisay', 'country_id' => 175  ],
            ['name' => 'Tanauan', 'country_id' => 175  ],
            ['name' => 'Tandag', 'country_id' => 175  ],
            ['name' => 'Tangub', 'country_id' => 175  ],
            ['name' => 'Tanjay', 'country_id' => 175  ],
            ['name' => 'Tarlac City', 'country_id' => 175  ],
            ['name' => 'Tayabas', 'country_id' => 175  ],
            ['name' => 'Toledo', 'country_id' => 175  ],
            ['name' => 'Trece Martires', 'country_id' => 175  ],
            ['name' => 'Tuguegarao', 'country_id' => 175  ],
            ['name' => 'Urdaneta', 'country_id' => 175  ],
            ['name' => 'Valencia', 'country_id' => 175  ],
            ['name' => 'Valenzuela', 'country_id' => 175  ],
            ['name' => 'Victorias', 'country_id' => 175  ],
            ['name' => 'Vigan', 'country_id' => 175  ],
            ['name' => 'Zamboanga City', 'country_id' => 175]
        ];

        DB::table('cities')->insert($cities);
    }
}
